-- trucate everything and reload the data from scratch
truncate table NEWS_PIPELINE.BRONZE.RAW_NEWS;
truncate table NEWS_PIPELINE.DBT_DEV_SILVER.SILVER_CLEAN_NEWS;

select * from NEWS_PIPELINE.DBT_DEV_STAGING.STG_RAW_NEWS;

truncate table NEWS_PIPELINE.DBT_DEV_GOLD.GOLD_ARTICLES_BY_CATEGORY_HOUR;

truncate table NEWS_PIPELINE.DBT_DEV_GOLD.GOLD_CONTENT_QUALITY;

truncate table NEWS_PIPELINE.DBT_DEV_GOLD.GOLD_LATEST_HEADLINES;

truncate table NEWS_PIPELINE.DBT_DEV_GOLD.GOLD_PUBLISHING_PATTERNS;

truncate table NEWS_PIPELINE.DBT_DEV_GOLD.GOLD_TOP_SOURCES;


--prods
truncate table NEWS_PIPELINE.PROD_GOLD.GOLD_ARTICLES_BY_CATEGORY_HOUR;
truncate table NEWS_PIPELINE.PROD_GOLD.GOLD_CONTENT_QUALITY;
truncate table NEWS_PIPELINE.PROD_GOLD.GOLD_LATEST_HEADLINES;
truncate table NEWS_PIPELINE.PROD_GOLD.GOLD_PUBLISHING_PATTERNS;
truncate table NEWS_PIPELINE.PROD_GOLD.GOLD_TOP_SOURCES;

truncate table NEWS_PIPELINE.PROD_SILVER.SILVER_CLEAN_NEWS;
--truncate table NEWS_PIPELINE.PROD_STAGING.STG_RAW_NEWS;
